# -*- coding: utf-8 -*-
"""VIT_MODEL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10rC7mCKdGeKZQKQIwMx9psIJuLf_d0YS
"""

from google.colab import drive
drive.mount('/content/drive')





import os
import numpy as np
from sklearn.model_selection import train_test_split
from torchvision import datasets

BASE_PATH = "/content/drive/MyDrive/walnut_dataset_unprocessed"
SAVE_PATH = "/content/drive/MyDrive/dataset_metadata"

os.makedirs(SAVE_PATH, exist_ok=True)

dataset = datasets.ImageFolder(BASE_PATH)

labels = np.array(dataset.targets)
indices = np.arange(len(dataset))

print("Total Images:", len(dataset))
print("Class Distribution:", np.bincount(labels))

train_idx, temp_idx = train_test_split(
    indices,
    test_size=0.30,
    stratify=labels,
    random_state=42
)

val_idx, test_idx = train_test_split(
    temp_idx,
    test_size=0.50,
    stratify=labels[temp_idx],
    random_state=42
)

def check_distribution(name, idx):
    print(f"\n{name} distribution:")
    print(np.bincount(labels[idx]))

check_distribution("Train", train_idx)
check_distribution("Validation", val_idx)
check_distribution("Test", test_idx)

np.savez(
    os.path.join(SAVE_PATH, "split_indices.npz"),
    train_idx=train_idx,
    val_idx=val_idx,
    test_idx=test_idx
)

print("Dataset preparation complete. Indices saved.")

import numpy as np
from torchvision import datasets

BASE_PATH = "/content/drive/MyDrive/walnut_dataset_unprocessed"
META_PATH = "/content/drive/MyDrive/dataset_metadata/split_indices.npz"

dataset = datasets.ImageFolder(BASE_PATH)
labels = np.array(dataset.targets)

data = np.load(META_PATH)

train_idx = data["train_idx"]
val_idx   = data["val_idx"]
test_idx  = data["test_idx"]

def check_dist(name, idx):
    counts = np.bincount(labels[idx])
    print(f"{name} distribution: {counts}")

check_dist("Train", train_idx)
check_dist("Validation", val_idx)
check_dist("Test", test_idx)

import torch
from torch.utils.data import DataLoader, Subset
from torchvision import transforms

# ==============================
# Define Transforms (ViT style)
# ==============================

train_transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406],
                         [0.229,0.224,0.225])
])

test_transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406],
                         [0.229,0.224,0.225])
])

# ==============================
# Reload dataset with transforms
# ==============================

dataset_train = datasets.ImageFolder(BASE_PATH, transform=train_transform)
dataset_test  = datasets.ImageFolder(BASE_PATH, transform=test_transform)

# ==============================
# Create subsets using saved indices
# ==============================

train_dataset = Subset(dataset_train, train_idx)
val_dataset   = Subset(dataset_test, val_idx)
test_dataset  = Subset(dataset_test, test_idx)

# ==============================
# Create DataLoaders
# ==============================

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader   = DataLoader(val_dataset, batch_size=16, shuffle=False)
test_loader  = DataLoader(test_dataset, batch_size=16, shuffle=False)

print("DataLoaders ready.")

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Count samples per class in training set
train_labels = labels[train_idx]
class_counts = np.bincount(train_labels)

print("Training class distribution:", class_counts)

# Compute class weights
class_weights = 1.0 / class_counts
class_weights = class_weights / class_weights.sum()

print("Class weights:", class_weights)

# Move weights to correct device
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float).to(device)

criterion = torch.nn.CrossEntropyLoss(weight=class_weights_tensor)

import torch
import torch.nn as nn
import torch.optim as optim
import timm
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import os
from torch.cuda.amp import GradScaler, autocast

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# =========================
# Model: ViT-B/16
# =========================
model = timm.create_model(
    "vit_base_patch16_224",
    pretrained=True,
    num_classes=2
)

# 🔥 Freeze backbone (FAST)
for param in model.parameters():
    param.requires_grad = False

# Unfreeze classifier head only
for param in model.head.parameters():
    param.requires_grad = True

model = model.to(device)

# =========================
# Optimizer (only head params)
# =========================
optimizer = optim.AdamW(model.head.parameters(), lr=1e-4, weight_decay=1e-4)

scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode='min',
    factor=0.5,
    patience=2
)

# =========================
# Training Settings
# =========================
EPOCHS = 8   # Reduced
early_stop_patience = 3
best_val_loss = float("inf")
patience_counter = 0

train_losses, val_losses = [], []
train_accs, val_accs = [], []

# Mixed precision scaler
scaler = GradScaler()

# =========================
# Training Loop
# =========================
for epoch in range(EPOCHS):

    # ---- TRAIN ----
    model.train()
    running_loss, correct, total = 0, 0, 0

    for images, labels_batch in train_loader:
        images = images.to(device)
        labels_batch = labels_batch.to(device)

        optimizer.zero_grad()

        # 🔥 Mixed precision (FASTER)
        with autocast():
            outputs = model(images)
            loss = criterion(outputs, labels_batch)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        total += labels_batch.size(0)
        correct += predicted.eq(labels_batch).sum().item()

    train_loss = running_loss / len(train_loader)
    train_acc = 100. * correct / total

    # ---- VALIDATION ----
    model.eval()
    val_loss, correct, total = 0, 0, 0

    with torch.no_grad():
        for images, labels_batch in val_loader:
            images = images.to(device)
            labels_batch = labels_batch.to(device)

            with autocast():
                outputs = model(images)
                loss = criterion(outputs, labels_batch)

            val_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            total += labels_batch.size(0)
            correct += predicted.eq(labels_batch).sum().item()

    val_loss /= len(val_loader)
    val_acc = 100. * correct / total

    scheduler.step(val_loss)

    train_losses.append(train_loss)
    val_losses.append(val_loss)
    train_accs.append(train_acc)
    val_accs.append(val_acc)

    print(f"\nEpoch [{epoch+1}/{EPOCHS}]")
    print(f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.2f}%")
    print(f"Val   Loss: {val_loss:.4f} | Val   Acc: {val_acc:.2f}%")

    # ---- Early Stopping ----
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), "/content/drive/MyDrive/best_vit_model.pth")
        patience_counter = 0
    else:
        patience_counter += 1

    if patience_counter >= early_stop_patience:
        print("Early stopping triggered.")
        break

print("Training Complete.")

plt.figure()
plt.plot(train_losses, label="Train Loss")
plt.plot(val_losses, label="Val Loss")
plt.legend()
plt.title("Loss Curve")
plt.savefig("/content/drive/MyDrive/vit_loss_curve.png")
plt.show()

plt.figure()
plt.plot(train_accs, label="Train Acc")
plt.plot(val_accs, label="Val Acc")
plt.legend()
plt.title("Accuracy Curve")
plt.savefig("/content/drive/MyDrive/vit_accuracy_curve.png")
plt.show()

# Load best model
model.load_state_dict(torch.load("/content/drive/MyDrive/best_vit_model.pth"))
model.eval()

all_preds = []
all_labels = []

with torch.no_grad():
    for images, labels_batch in test_loader:
        images = images.to(device)
        labels_batch = labels_batch.to(device)

        outputs = model(images)
        _, predicted = torch.max(outputs, 1)

        all_preds.extend(predicted.cpu().numpy())
        all_labels.extend(labels_batch.cpu().numpy())

# Classification Report
report = classification_report(
    all_labels,
    all_preds,
    target_names=["Anthracnose", "Healthy"]
)

print("\nClassification Report:\n")
print(report)

# Save report
with open("/content/drive/MyDrive/vit_classification_report.txt", "w") as f:
    f.write(report)

# Confusion Matrix
cm = confusion_matrix(all_labels, all_preds)

plt.figure()
sns.heatmap(cm, annot=True, fmt="d",
            xticklabels=["Anthracnose", "Healthy"],
            yticklabels=["Anthracnose", "Healthy"])
plt.title("Confusion Matrix")
plt.savefig("/content/drive/MyDrive/vit_confusion_matrix.png")
plt.show()